
import java.awt.Color;
import java.awt.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mamoudou Diallo
 */
public class ApprendLesComposants extends javax.swing.JFrame {

    /**
     * Creates new form ApprendLesComposants
     */
    
    
    public ApprendLesComposants() {
        initComponents(); //Création de l'inferface( généré par l'EDI)*
        
        // remplir la JComboBox et JList
        fielJCombo();
        fielJList();
    }
    
    // Méthode permettant de remplir la ComboBox
    public void fielJCombo()
    {
        Animals.addItem("Choix d'un animal");
        Animals.addItem("Lapin");
        Animals.addItem("Oiseau");
        Animals.addItem("Chaval");
        Animals.addItem("Tigre");
        Animals.addItem("Giraffe");
        Animals.addItem("Coq");
        
    }
    
    // Méthode permettant de remplir la JList
    public void fielJList()
    {
        DefaultListModel model= new DefaultListModel();
        Plants.setModel(model);
        model.addElement("Choix d'une plante");
        model.addElement("Bananier");
        model.addElement("Cocotier");
        model.addElement("Gimgembre");
        model.addElement("Oranger");   
        model.addElement("Avocatier");
        model.addElement("Goyavier");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        font = new javax.swing.ButtonGroup();
        couleur = new javax.swing.ButtonGroup();
        est = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Animals = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        BGigi = new javax.swing.JRadioButton();
        BSerif = new javax.swing.JRadioButton();
        BPalace = new javax.swing.JRadioButton();
        BImpact = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Brouge = new javax.swing.JButton();
        Bjaune = new javax.swing.JButton();
        Bvert = new javax.swing.JButton();
        ouest = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Plants = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        BGris = new javax.swing.JCheckBox();
        BBleu = new javax.swing.JCheckBox();
        BRouge = new javax.swing.JCheckBox();
        BVert = new javax.swing.JCheckBox();
        BJaune = new javax.swing.JCheckBox();
        BMagenta = new javax.swing.JCheckBox();
        nord = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sud = new javax.swing.JPanel();
        Effacer = new javax.swing.JButton();
        centre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        Option = new javax.swing.JMenu();
        Quitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        est.setPreferredSize(new java.awt.Dimension(250, 350));
        est.setLayout(new java.awt.GridLayout(11, 1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Liste des animaux");
        est.add(jLabel6);

        Animals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalsActionPerformed(evt);
            }
        });
        est.add(Animals);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Choisir la fonte");
        est.add(jLabel3);

        font.add(BGigi);
        BGigi.setText("Gigi");
        BGigi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGigiActionPerformed(evt);
            }
        });
        est.add(BGigi);

        font.add(BSerif);
        BSerif.setText("Serif");
        BSerif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSerifActionPerformed(evt);
            }
        });
        est.add(BSerif);

        font.add(BPalace);
        BPalace.setText("Palace Script MT");
        BPalace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPalaceActionPerformed(evt);
            }
        });
        est.add(BPalace);

        font.add(BImpact);
        BImpact.setText("Impact");
        BImpact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BImpactActionPerformed(evt);
            }
        });
        est.add(BImpact);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Choisir la couleur de fond");
        est.add(jLabel4);

        Brouge.setText("Rouge");
        Brouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrougeActionPerformed(evt);
            }
        });
        est.add(Brouge);

        Bjaune.setText("Jaune");
        Bjaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BjauneActionPerformed(evt);
            }
        });
        est.add(Bjaune);

        Bvert.setText("Vert");
        Bvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvertActionPerformed(evt);
            }
        });
        est.add(Bvert);

        getContentPane().add(est, java.awt.BorderLayout.EAST);

        ouest.setPreferredSize(new java.awt.Dimension(250, 350));
        ouest.setLayout(new java.awt.GridLayout(9, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Liste des plantes");
        ouest.add(jLabel5);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(258, 258));

        Plants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlantsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Plants);

        ouest.add(jScrollPane2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Choisir la couleur du texte");
        ouest.add(jLabel2);

        couleur.add(BGris);
        BGris.setText("Gris");
        BGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGrisActionPerformed(evt);
            }
        });
        ouest.add(BGris);

        couleur.add(BBleu);
        BBleu.setText("Bleu");
        BBleu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBleuActionPerformed(evt);
            }
        });
        ouest.add(BBleu);
        BBleu.getAccessibleContext().setAccessibleDescription("");

        couleur.add(BRouge);
        BRouge.setText("Rouge");
        BRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRougeActionPerformed(evt);
            }
        });
        ouest.add(BRouge);

        couleur.add(BVert);
        BVert.setText("Vert");
        BVert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVertActionPerformed(evt);
            }
        });
        ouest.add(BVert);

        couleur.add(BJaune);
        BJaune.setText("Jaune");
        BJaune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJauneActionPerformed(evt);
            }
        });
        ouest.add(BJaune);

        couleur.add(BMagenta);
        BMagenta.setText("Magenta");
        BMagenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMagentaActionPerformed(evt);
            }
        });
        ouest.add(BMagenta);

        getContentPane().add(ouest, java.awt.BorderLayout.WEST);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Apprend les composants");
        nord.add(jLabel1);

        getContentPane().add(nord, java.awt.BorderLayout.NORTH);

        Effacer.setText("Effacer");
        Effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EffacerActionPerformed(evt);
            }
        });
        sud.add(Effacer);

        getContentPane().add(sud, java.awt.BorderLayout.SOUTH);

        centre.setPreferredSize(new java.awt.Dimension(300, 131));
        centre.setLayout(new java.awt.GridLayout(1, 1));

        Edition.setColumns(20);
        Edition.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        centre.add(jScrollPane1);

        getContentPane().add(centre, java.awt.BorderLayout.CENTER);

        Option.setText("Option");

        Quitter.setText("Quitter");
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });
        Option.add(Quitter);

        jMenuBar1.add(Option);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterActionPerformed
        // Permet de sortir du programme
        System.exit(0);
    }//GEN-LAST:event_QuitterActionPerformed

    private void EffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EffacerActionPerformed
        // Permet de vider le texte dans la zone d'édition
        Edition.setText("");
        Edition.setBackground(Color.white);
    }//GEN-LAST:event_EffacerActionPerformed

    private void BBleuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBleuActionPerformed
        // Permet de changer la couleur de la fonte (La police d'écriture) en Bleu
        Edition.setForeground(Color.blue);
    }//GEN-LAST:event_BBleuActionPerformed

    private void BRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRougeActionPerformed
        // Permet de changer la couleur de la fonte (La police d'écriture) en Rouge
        Edition.setForeground(Color.red);
    }//GEN-LAST:event_BRougeActionPerformed

    private void BVertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVertActionPerformed
        // Permet de changer la couleur de la fonte (La police d'écriture) en Vert
        Edition.setForeground(Color.green);
    }//GEN-LAST:event_BVertActionPerformed

    private void BJauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BJauneActionPerformed
        // Permet de changer la couleur de la fonte (La police d'écriture) en Jaune
        Edition.setForeground(Color.yellow);
    }//GEN-LAST:event_BJauneActionPerformed

    private void BMagentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMagentaActionPerformed
        // Permet de changer la couleur de la fonte (La police d'écriture) en Orange
        Edition.setForeground(Color.magenta);
    }//GEN-LAST:event_BMagentaActionPerformed

    private void BGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGrisActionPerformed
        // Permet de changer la couleur de la fonte (La police d'écriture) en Gris
        Edition.setForeground(Color.gray);
    }//GEN-LAST:event_BGrisActionPerformed

    private void BGigiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGigiActionPerformed
        // Permet de changer la fonte (La police d'écriture) en Gigi
        Edition.setFont(new Font("Gigi", 3, 36));
    }//GEN-LAST:event_BGigiActionPerformed

    private void BSerifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSerifActionPerformed
        // Permet de changer la fonte (La police d'écriture) en Serif
        Edition.setFont(new Font("Serif", 3, 36));
    }//GEN-LAST:event_BSerifActionPerformed

    private void BPalaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPalaceActionPerformed
        // Permet de changer la fonte en (La police d'écriture) Algerian
        Edition.setFont(new Font("Palace Script MT", 3, 36));
    }//GEN-LAST:event_BPalaceActionPerformed

    private void BImpactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BImpactActionPerformed
        // Permet de changer la fonte en (La police d'écriture) Impact
        Edition.setFont(new Font("Impact", 3, 36));
    }//GEN-LAST:event_BImpactActionPerformed

    private void AnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalsActionPerformed
        // Pemet de recuperer l'élément selectionner dans la JComboBox 
        String s=Animals.getSelectedItem().toString();
        
        // Conditiion permettant de ne pas pouvoir cliquer sur "Choix d'un animal"
        if (s!="Choix d'un animal")
        {
            Edition.append(s + "\n");
        }
            
    }//GEN-LAST:event_AnimalsActionPerformed

    private void PlantsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlantsMouseClicked
        // Pemet de recuperer l'indice selectionner dans la JList
        int p=Plants.getSelectedIndex();
        
        // Conditiion permettant de ne pas pouvoir cliquer sur "Choix d'une plante"
        if (p!=0)
        {
           
                Edition.append(Plants.getModel().getElementAt(p)+ "\n");
             
        }
    }//GEN-LAST:event_PlantsMouseClicked

    private void BvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvertActionPerformed
        // Permet de changer la couleur du fond de la fonte (La police d'écriture) en Rouge
        Edition.setBackground(Color.green);
    }//GEN-LAST:event_BvertActionPerformed

    private void BjauneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BjauneActionPerformed
        // Permet de changer la couleur du fond de la fonte (La police d'écriture) en Jaune
        Edition.setBackground(Color.yellow);
    }//GEN-LAST:event_BjauneActionPerformed

    private void BrougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrougeActionPerformed
        // Permet de changer la couleur du fond de la fonte (La police d'écriture) en Vert
        Edition.setBackground(Color.red);
    }//GEN-LAST:event_BrougeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprendLesComposants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprendLesComposants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprendLesComposants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprendLesComposants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprendLesComposants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Animals;
    private javax.swing.JCheckBox BBleu;
    private javax.swing.JRadioButton BGigi;
    private javax.swing.JCheckBox BGris;
    private javax.swing.JRadioButton BImpact;
    private javax.swing.JCheckBox BJaune;
    private javax.swing.JCheckBox BMagenta;
    private javax.swing.JRadioButton BPalace;
    private javax.swing.JCheckBox BRouge;
    private javax.swing.JRadioButton BSerif;
    private javax.swing.JCheckBox BVert;
    private javax.swing.JButton Bjaune;
    private javax.swing.JButton Brouge;
    private javax.swing.JButton Bvert;
    private javax.swing.JTextArea Edition;
    private javax.swing.JButton Effacer;
    private javax.swing.JMenu Option;
    private javax.swing.JList<String> Plants;
    private javax.swing.JMenuItem Quitter;
    private javax.swing.JPanel centre;
    private javax.swing.ButtonGroup couleur;
    private javax.swing.JPanel est;
    private javax.swing.ButtonGroup font;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel nord;
    private javax.swing.JPanel ouest;
    private javax.swing.JPanel sud;
    // End of variables declaration//GEN-END:variables
}
